export const renderDashboardHtml = (): string => `<!doctype html>
<html lang="es">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Polymarket Bot Dashboard</title>
  <style>
    :root{--bg:#f5efe6;--ink:#132533;--muted:#60717c;--panel:#fffdfa;--line:rgba(19,37,51,.1);--teal:#0f7b72;--gold:#d39a39;--green:#209a57;--red:#be3f38;--amber:#c17a16;--mono:"Cascadia Code","Consolas",monospace;--sans:"Aptos","Segoe UI Variable","Trebuchet MS",sans-serif}
    *{box-sizing:border-box}html,body{margin:0;min-height:100%;background:radial-gradient(circle at top left,rgba(15,123,114,.14),transparent 26%),radial-gradient(circle at top right,rgba(211,154,57,.14),transparent 28%),linear-gradient(180deg,var(--bg),#ede5da);color:var(--ink);font-family:var(--sans)}
    body{padding:20px}.shell{max-width:1440px;margin:0 auto}.hero,.panel,.metric{background:rgba(255,253,250,.92);border:1px solid var(--line);border-radius:24px;box-shadow:0 18px 50px rgba(19,37,51,.08)}
    .hero{padding:24px;background:linear-gradient(135deg,rgba(14,37,52,.97),rgba(23,73,99,.92));color:#fbf7f0}.hero-top{display:flex;justify-content:space-between;gap:16px;align-items:flex-start}.eyebrow{display:inline-flex;gap:10px;align-items:center;font-size:.82rem;text-transform:uppercase;letter-spacing:.14em;color:rgba(251,247,240,.74)}
    .dot{width:10px;height:10px;border-radius:999px;background:#77e8bf;box-shadow:0 0 0 0 rgba(119,232,191,.45);animation:pulse 2s infinite}@keyframes pulse{0%{box-shadow:0 0 0 0 rgba(119,232,191,.45)}70%{box-shadow:0 0 0 12px rgba(119,232,191,0)}100%{box-shadow:0 0 0 0 rgba(119,232,191,0)}}
    h1{margin:12px 0 10px;font-size:clamp(2rem,4vw,3.5rem);line-height:.95;letter-spacing:-.05em;max-width:9ch}.hero p{margin:0;max-width:70ch;color:rgba(251,247,240,.76);line-height:1.6}
    .hero-actions{display:flex;flex-direction:column;align-items:flex-end;gap:12px}.pills,.hero-stats,.metrics,.main,.mini-grid,.ops-grid{display:grid;gap:14px}.pills{grid-auto-flow:column;grid-auto-columns:max-content}
    .pill,.badge,.status{display:inline-flex;align-items:center;gap:8px;padding:9px 12px;border-radius:999px;font-size:.86rem}.pill{background:rgba(255,255,255,.09);border:1px solid rgba(255,255,255,.09)}.pill strong{font-weight:700}
    .button{border:0;border-radius:999px;padding:12px 18px;font-weight:700;background:linear-gradient(135deg,#ffd271,#ffbf59);color:#20303a;cursor:pointer;box-shadow:0 12px 24px rgba(255,210,113,.2)}
    .hero-stats{grid-template-columns:repeat(4,minmax(0,1fr));margin-top:20px}.hero-stat{padding:15px 16px;border-radius:18px;background:rgba(255,255,255,.08);border:1px solid rgba(255,255,255,.08)}.hero-stat label{display:block;font-size:.84rem;color:rgba(251,247,240,.7);margin-bottom:8px}.hero-stat strong{font-size:1.25rem}.hero-stat small{display:block;margin-top:6px;color:rgba(251,247,240,.68)}
    .metrics{grid-template-columns:repeat(4,minmax(0,1fr));margin-top:18px}.metric{padding:16px;display:flex;flex-direction:column;gap:12px;min-height:126px}.metric-top,.head{display:flex;justify-content:space-between;gap:12px;align-items:center}.metric-top{color:var(--muted);font-size:.9rem}.badge{padding:6px 10px;font-size:.76rem;font-weight:700}.badge.pos,.status.pos{background:rgba(32,154,87,.12);color:var(--green)}.badge.warn,.status.warn{background:rgba(193,122,22,.12);color:var(--amber)}.badge.danger,.status.danger{background:rgba(190,63,56,.12);color:var(--red)}.badge.neutral,.status.neutral{background:rgba(19,37,51,.08);color:var(--ink)}
    .metric-value{font-size:clamp(1.55rem,2.5vw,2.2rem);font-weight:800;letter-spacing:-.05em}.metric-note{display:flex;justify-content:space-between;gap:10px;color:var(--muted);font-size:.9rem}.mono{font-family:var(--mono)}
    .main{grid-template-columns:minmax(0,1.6fr) minmax(320px,.95fr);margin-top:18px}.stack{display:grid;gap:18px}.panel{padding:20px}.head h2{margin:0;font-size:1.1rem;letter-spacing:-.03em}.head small,.muted{color:var(--muted)}
    .chart{padding:16px;border-radius:18px;background:linear-gradient(180deg,rgba(15,123,114,.06),rgba(19,37,51,.02));border:1px solid rgba(15,123,114,.12)}.chart-top{display:flex;justify-content:space-between;gap:12px;align-items:flex-start;margin-bottom:10px}.chart-top strong{display:block;font-size:1.4rem}.legend{display:flex;gap:14px;flex-wrap:wrap;color:var(--muted);font-size:.9rem}.legend span{display:inline-flex;align-items:center;gap:8px}.swatch{width:12px;height:12px;border-radius:999px}.swatch.real{background:var(--teal)}.swatch.exp{background:var(--gold)}.swatch.shadow{background:#4c7ef3}#profit-chart{width:100%;height:250px;display:block}
    .mini-grid{grid-template-columns:repeat(2,minmax(0,1fr));margin-top:14px}.mini{padding:15px;border-radius:18px;background:var(--panel);border:1px solid var(--line)}.mini h3{margin:0 0 8px;font-size:1rem}.mini strong{display:block;font-size:1.35rem}.bar{width:100%;height:9px;margin:10px 0;border-radius:999px;background:rgba(19,37,51,.08);overflow:hidden}.bar span{display:block;height:100%;width:0;background:linear-gradient(90deg,var(--teal),#36b2a9);transition:width .5s ease}
    .tiny{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px;color:var(--muted);font-size:.86rem}.table{overflow:auto;border:1px solid var(--line);border-radius:18px}table{width:100%;border-collapse:collapse;min-width:920px}th,td{padding:13px 14px;text-align:left;border-bottom:1px solid var(--line);vertical-align:top}th{background:#f3f7f6;color:var(--muted);font-size:.8rem;text-transform:uppercase;letter-spacing:.08em}
    .row{display:grid;gap:6px}.order{display:inline-block;margin:0 8px 6px 0;padding:6px 8px;border-radius:10px;background:rgba(19,37,51,.05)}.feed,.list{display:grid;gap:10px}.feed-item,.ops,.item{padding:14px;border-radius:18px;background:var(--panel);border:1px solid var(--line)}.feed-item strong,.item strong{display:block;margin-bottom:6px}.ops-grid{grid-template-columns:repeat(2,minmax(0,1fr))}
    .ops label{display:block;color:var(--muted);font-size:.84rem;margin-bottom:7px}.ops strong{font-size:1.05rem}.empty{padding:18px;text-align:center;border-radius:18px;border:1px dashed rgba(19,37,51,.14);color:var(--muted);background:rgba(255,255,255,.45)}
    @media(max-width:1180px){.metrics,.hero-stats{grid-template-columns:repeat(2,minmax(0,1fr))}.main{grid-template-columns:1fr}}@media(max-width:760px){body{padding:12px}.hero-top{flex-direction:column}.hero-actions{align-items:flex-start}.metrics,.hero-stats,.mini-grid,.ops-grid{grid-template-columns:1fr}table{min-width:760px}}
  </style>
</head>
<body>
  <div class="shell">
    <header class="hero">
      <div class="hero-top">
        <div>
          <div class="eyebrow"><span class="dot"></span> Polymarket trading room</div>
          <h1>Bot operations dashboard</h1>
          <p>Seguimiento clinico en tiempo real para validar <strong>binary_arb</strong> rumbo a <strong>us-east</strong>: shadow fills, frescura del libro, desconexiones del feed y reservas abiertas antes de pasar a capital real.</p>
        </div>
        <div class="hero-actions">
          <div class="pills" id="hero-pills"></div>
          <button class="button" id="refresh-btn" type="button">Actualizar ahora</button>
        </div>
      </div>
      <div class="hero-stats" id="hero-stats"></div>
    </header>
    <section class="metrics" id="metrics"></section>
    <section class="main">
      <div class="stack">
        <section class="panel">
          <div class="head"><h2>PnL acumulado</h2><small id="chart-caption">Sin datos</small></div>
          <div class="chart">
            <div class="chart-top">
              <div><strong id="chart-head">$0.00</strong><small class="muted" id="chart-sub">Realized PnL</small></div>
              <div class="legend"><span><i class="swatch real"></i>Actual</span><span><i class="swatch shadow"></i>Shadow</span><span><i class="swatch exp"></i>Expected</span></div>
            </div>
            <svg id="profit-chart" viewBox="0 0 860 250" preserveAspectRatio="none"></svg>
          </div>
          <div class="mini-grid" id="strategy-grid"></div>
        </section>
        <section class="panel">
          <div class="head"><h2>Ordenes y trades recientes</h2><small id="trades-caption">Ultimas ejecuciones</small></div>
          <div class="table">
            <table>
              <thead><tr><th>Trade</th><th>Estado</th><th>Size</th><th>PnL</th><th>Ordenes</th><th>Notas</th></tr></thead>
              <tbody id="trades-body"></tbody>
            </table>
          </div>
        </section>
      </div>
      <div class="stack">
        <section class="panel">
          <div class="head"><h2>Actividad reciente</h2><small id="activity-caption">Eventos del bot</small></div>
          <div class="feed" id="activity"></div>
        </section>
        <section class="panel">
          <div class="head"><h2>Oportunidades</h2><small id="opps-caption">Calidad del flujo</small></div>
          <div class="ops-grid" id="opp-cards"></div>
          <div class="list" id="rejections"></div>
          <div class="list" id="near-misses"></div>
          <div class="list" id="recent-opps"></div>
        </section>
        <section class="panel">
          <div class="head"><h2>Salud operativa</h2><small id="ops-caption">Infraestructura y riesgo</small></div>
          <div class="ops-grid" id="ops-grid"></div>
          <div class="list" id="errors"></div>
          <small class="muted" id="foot-note"></small>
        </section>
      </div>
    </section>
  </div>
  <script>
    var els={heroPills:document.getElementById('hero-pills'),heroStats:document.getElementById('hero-stats'),metrics:document.getElementById('metrics'),chartCaption:document.getElementById('chart-caption'),chartHead:document.getElementById('chart-head'),chartSub:document.getElementById('chart-sub'),chart:document.getElementById('profit-chart'),strategyGrid:document.getElementById('strategy-grid'),tradesBody:document.getElementById('trades-body'),tradesCaption:document.getElementById('trades-caption'),activityCaption:document.getElementById('activity-caption'),activity:document.getElementById('activity'),oppsCaption:document.getElementById('opps-caption'),oppCards:document.getElementById('opp-cards'),rejections:document.getElementById('rejections'),nearMisses:document.getElementById('near-misses'),recentOpps:document.getElementById('recent-opps'),opsCaption:document.getElementById('ops-caption'),opsGrid:document.getElementById('ops-grid'),errors:document.getElementById('errors'),foot:document.getElementById('foot-note'),refresh:document.getElementById('refresh-btn')};
    var money=new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',minimumFractionDigits:2,maximumFractionDigits:2});
    var num=new Intl.NumberFormat('en-US',{maximumFractionDigits:2});
    var intNum=new Intl.NumberFormat('en-US',{maximumFractionDigits:0});
    function esc(v){return String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;')}
    function usd(v){return money.format(Number(v||0))} function pct(v){return (Number(v||0)*100).toFixed(1)+'%'} function n(v){return num.format(Number(v||0))} function i(v){return intNum.format(Number(v||0))}
    function ts(v){return v?new Intl.DateTimeFormat('es-AR',{dateStyle:'short',timeStyle:'medium',hour12:false}).format(new Date(v)):'n/a'}
    function ago(v){if(!v)return'n/a';var d=Math.max(0,Date.now()-Number(v)),s=Math.floor(d/1000);if(s<60)return s+'s';var m=Math.floor(s/60);if(m<60)return m+'m';var h=Math.floor(m/60);if(h<24)return h+'h';return Math.floor(h/24)+'d'}
    function sum(snapshot,key){return [snapshot.arbitrage,snapshot.ceilingArbitrage,snapshot.negRiskArbitrage,snapshot.lateResolution].filter(Boolean).reduce(function(t,x){return t+Number(x[key]||0)},0)}
    function capture(snapshot){var seen=sum(snapshot,'opportunitiesSeen');var cap=sum(snapshot,'opportunitiesCaptured');return seen>0?cap/seen:0}
    function pill(label,value,tone){return '<span class="pill '+(tone||'')+'"><strong>'+esc(label)+'</strong>'+esc(value)+'</span>'}
    function heroStat(label,value,note){return '<div class="hero-stat"><label>'+esc(label)+'</label><strong>'+esc(value)+'</strong><small>'+esc(note)+'</small></div>'}
    function metric(label,value,badge,tone,note){return '<article class="metric"><div class="metric-top"><span>'+esc(label)+'</span><span class="badge '+esc(tone)+'">'+esc(badge)+'</span></div><div class="metric-value">'+esc(value)+'</div><div class="metric-note"><span>'+esc(note)+'</span><code class="mono">'+esc(new Date().toLocaleTimeString('es-AR',{hour12:false}))+'</code></div></article>'}
    function mini(title,headline,caption,fill,meta){return '<article class="mini"><h3>'+esc(title)+'</h3><strong>'+esc(headline)+'</strong><div class="muted">'+esc(caption)+'</div><div class="bar"><span data-fill="'+Math.max(6,Math.min(100,Number(fill||0)*100)).toFixed(1)+'"></span></div><div class="tiny"><span>'+esc(meta[0])+'</span><span>'+esc(meta[1])+'</span><span>'+esc(meta[2])+'</span><span>'+esc(meta[3])+'</span></div></article>'}
    function ops(label,value,note){return '<div class="ops"><label>'+esc(label)+'</label><strong>'+esc(value)+'</strong><div class="muted">'+esc(note)+'</div></div>'}
    function renderHero(payload){var s=payload.snapshot,a=payload.analytics,g=s.tradingGuard||{},enabled=g.tradingEnabled!==false,elapsedMs=Math.max(0,Date.now()-s.startedAt),progress=Math.min(1,elapsedMs/86400000);els.heroPills.innerHTML=[pill('Mode',payload.dryRun?'Dry run':'Live',payload.dryRun?'warn':'pos'),pill('Trading',enabled?'Enabled':'Paused',enabled?'pos':'danger'),pill('WebSocket',s.scanner.websocketConnected?'Connected':'Disconnected',s.scanner.websocketConnected?'pos':'danger'),pill('24h progress',pct(progress),progress>=1?'pos':'warn'),pill('Updated',ts(payload.generatedAt))].join('');els.heroStats.innerHTML=[heroStat('Shadow PnL',usd(a.tradeSummary.totalShadowRealizedProfitUsd),'Expected '+usd(a.tradeSummary.totalExpectedProfitUsd)),heroStat('Actual live PnL',usd(a.tradeSummary.totalRealizedProfitUsd),'Actual only, no shadow'),heroStat('Open notional',usd(s.execution.openNotionalUsd),'Reservations '+i(s.execution.openReservationsCount)),heroStat('Markets tracked',i(s.scanner.marketsTracked),'Tokens '+i(s.scanner.tokensTracked)),heroStat('Shadow fill rate',pct(a.tradeSummary.shadowFillRate),'Attempts '+i(a.tradeSummary.shadowAttempts)),heroStat('Trade throughput',i(a.tradeSummary.totalTrades),'Orders '+i(a.tradeSummary.submittedOrders)),heroStat('Run elapsed',n(elapsedMs/3600000)+' h','Target 24.0 h'),heroStat('WS disconnects',i(s.scanner.websocketDisconnects),'Feed interruptions observed')].join('')}
    function renderMetrics(payload){var s=payload.snapshot,a=payload.analytics,cap=capture(s),shadowRate=a.tradeSummary.shadowAttempts>0?a.tradeSummary.shadowFillRate:s.execution.shadowFillRate,effectivePnl=payload.dryRun?a.tradeSummary.totalShadowRealizedProfitUsd:(a.tradeSummary.totalRealizedProfitUsd||a.tradeSummary.totalShadowRealizedProfitUsd),pnlDrift=effectivePnl-a.tradeSummary.totalExpectedProfitUsd;els.metrics.innerHTML=[metric('Shadow realized',usd(a.tradeSummary.totalShadowRealizedProfitUsd),'paper truth',a.tradeSummary.totalShadowRealizedProfitUsd>=0?'pos':'danger','Avg '+usd(a.tradeSummary.averageShadowRealizedProfitUsd)),metric('Actual live realized',usd(a.tradeSummary.totalRealizedProfitUsd),'live only',a.tradeSummary.totalRealizedProfitUsd>=0?'neutral':'danger',payload.dryRun?'Dry run ignorando fills reales':'Avg '+usd(a.tradeSummary.averageRealizedProfitUsd)),metric('Expected edge',usd(a.tradeSummary.totalExpectedProfitUsd),'modeled edge','warn','Drift '+usd(pnlDrift)),metric('Shadow fill rate',pct(shadowRate),'paper execution',shadowRate>=.35?'pos':'warn',i(a.tradeSummary.shadowSuccesses)+' / '+i(a.tradeSummary.shadowAttempts)),metric('Capture rate',pct(cap),'opportunity retention',cap>=.15?'pos':'warn',i(sum(s,'opportunitiesCaptured'))+' captured'),metric('Stale books skipped',i(s.arbitrage.staleBooksSkipped||0),'execution freshness',(s.arbitrage.staleBooksSkipped||0)===0?'pos':'warn','Last age '+(s.arbitrage.lastBookAgeMs!==undefined?i(s.arbitrage.lastBookAgeMs)+'ms':'n/a')),metric('WS disconnects',i(s.scanner.websocketDisconnects||0),'feed stability',(s.scanner.websocketDisconnects||0)<=2?'pos':'warn','Reconnects '+i(s.scanner.websocketReconnects||0)),metric('Errors logged',i(a.totalErrors),'runtime health',a.totalErrors===0?'pos':'danger',a.latestErrorAt?'Last '+ago(a.latestErrorAt):'No errors yet')].join('')}
    function renderChart(analytics){var series=analytics.profitSeries||[];els.chartCaption.textContent=series.length?'Serie sobre '+i(series.length)+' puntos':'Sin operaciones';els.chartHead.textContent=usd(analytics.tradeSummary.totalShadowRealizedProfitUsd||analytics.tradeSummary.totalRealizedProfitUsd);els.chartSub.textContent='Shadow '+usd(analytics.tradeSummary.totalShadowRealizedProfitUsd)+' | actual '+usd(analytics.tradeSummary.totalRealizedProfitUsd)+' | expected '+usd(analytics.tradeSummary.totalExpectedProfitUsd);if(!series.length){els.chart.innerHTML='<foreignObject x="0" y="0" width="860" height="250"><div xmlns="http://www.w3.org/1999/xhtml" class="empty">Todavia no hay trades persistidos para dibujar la curva de PnL.</div></foreignObject>';return}var vals=[];series.forEach(function(p){vals.push(Number(p.cumulativeRealizedProfitUsd||0));vals.push(Number(p.cumulativeShadowRealizedProfitUsd||0));vals.push(Number(p.cumulativeExpectedProfitUsd||0))});var min=Math.min.apply(null,vals),max=Math.max.apply(null,vals);if(min===max){min-=1;max+=1}var w=860,h=250,px=26,py=22;function x(idx){var span=Math.max(1,series.length-1);return px+(idx/span)*(w-px*2)}function y(val){var ratio=(Number(val)-min)/(max-min||1);return h-py-ratio*(h-py*2)}function poly(key){return series.map(function(p,idx){return x(idx).toFixed(2)+','+y(p[key]).toFixed(2)}).join(' ')}var last=series[series.length-1],zero=y(0);els.chart.innerHTML='<line x1="'+px+'" y1="'+zero.toFixed(2)+'" x2="'+(w-px)+'" y2="'+zero.toFixed(2)+'" stroke="rgba(19,37,51,.16)" stroke-dasharray="4 6" /><polyline fill="none" stroke="rgba(211,154,57,.92)" stroke-width="3" stroke-linecap="round" stroke-linejoin="round" points="'+poly('cumulativeExpectedProfitUsd')+'" /><polyline fill="none" stroke="#4c7ef3" stroke-width="3.5" stroke-linecap="round" stroke-linejoin="round" points="'+poly('cumulativeShadowRealizedProfitUsd')+'" /><polyline fill="none" stroke="rgba(15,123,114,.96)" stroke-width="4" stroke-linecap="round" stroke-linejoin="round" points="'+poly('cumulativeRealizedProfitUsd')+'" /><circle cx="'+x(series.length-1).toFixed(2)+'" cy="'+y(last.cumulativeExpectedProfitUsd).toFixed(2)+'" r="4.5" fill="#d39a39" stroke="#fff" stroke-width="2" /><circle cx="'+x(series.length-1).toFixed(2)+'" cy="'+y(last.cumulativeShadowRealizedProfitUsd).toFixed(2)+'" r="5.2" fill="#4c7ef3" stroke="#fff" stroke-width="2.5" /><circle cx="'+x(series.length-1).toFixed(2)+'" cy="'+y(last.cumulativeRealizedProfitUsd).toFixed(2)+'" r="5.5" fill="#0f7b72" stroke="#fff" stroke-width="3" />'}
    function renderStrategies(analytics){var cards=[];(analytics.strategyPerformance||[]).slice(0,4).forEach(function(s){var effective=s.totalShadowRealizedProfitUsd||s.totalRealizedProfitUsd;var fill=s.shadowAttempts>0?s.shadowFillRate:s.winRate;cards.push(mini(s.strategyType,usd(effective),'Shadow '+usd(s.totalShadowRealizedProfitUsd)+' | Actual '+usd(s.totalRealizedProfitUsd),fill,['Trades '+i(s.trades),'Shadow fill '+pct(s.shadowFillRate),'Avg size '+n(s.averageTradeSize),'Expected '+usd(s.totalExpectedProfitUsd)]))});(analytics.modePerformance||[]).slice(0,2).forEach(function(m){var effective=m.totalShadowRealizedProfitUsd||m.totalRealizedProfitUsd;cards.push(mini(m.mode.toUpperCase(),usd(effective),'Actual '+usd(m.totalRealizedProfitUsd)+' | Shadow '+usd(m.totalShadowRealizedProfitUsd),m.shadowAttempts>0?m.shadowFillRate:m.successRate,['Trades '+i(m.trades),'Success '+i(m.successes),'Shadow '+i(m.shadowSuccesses)+' / '+i(m.shadowAttempts),'Execution mode']))});els.strategyGrid.innerHTML=cards.length?cards.join(''):'<div class="empty">Sin breakdown por estrategia todavia.</div>';requestAnimationFrame(function(){els.strategyGrid.querySelectorAll('.bar span').forEach(function(node){node.style.width=node.getAttribute('data-fill')+'%'})})}
    function renderTrades(analytics){var trades=analytics.recentTrades||[];els.tradesCaption.textContent=trades.length?'Mostrando '+i(trades.length)+' trades recientes':'Todavia no hay trades';if(!trades.length){els.tradesBody.innerHTML='<tr><td colspan="6"><div class="empty">El bot aun no registro trades en el journal.</div></td></tr>';return}els.tradesBody.innerHTML=trades.map(function(t){var isPaper=t.mode==='paper',success=isPaper?Boolean(t.shadowFillSuccess):Boolean(t.success),pnl=isPaper?Number(t.shadowRealizedProfitUsd||0):Number(t.realizedProfitUsd||0),pnlLabel=isPaper?'shadow':'actual',slip=isPaper?Number(t.shadowRealizedSlippageUsd||0):Number(t.realizedSlippageUsd||0),orders=[].concat(t.orderIds||[]).concat(t.hedgeOrderIds||[]).slice(0,3).map(function(id){return '<span class="order mono">'+esc(id)+'</span>'}).join('')||'<span class="muted">Sin order ids</span>',primaryNote=isPaper?(t.shadowFillReason||((t.notes&&t.notes[0])||'Shadow evaluation')):((t.notes&&t.notes[0])||'Sin observaciones');return '<tr><td><div class="row"><strong>'+esc(t.slug)+'</strong><small class="muted">'+esc((t.strategyType||'unknown')+' | '+t.mode+' | '+ts(t.timestamp))+'</small></div></td><td><span class="status '+(success?'pos':'danger')+'">'+(success?(isPaper?'Shadow fill':'Executed'):(isPaper?'Not fillable':'Failed'))+'</span></td><td><div class="row"><strong>'+esc(n(t.tradeSize))+'</strong><small class="muted">'+esc(t.resolvedOutcome||'paired')+'</small></div></td><td><div class="row"><strong>'+esc(usd(pnl))+'</strong><small class="muted">'+esc(pnlLabel+' pnl | expected '+usd(t.expectedProfitUsd)+' | slip '+usd(slip))+'</small></div></td><td>'+orders+'<div class="muted">'+esc('orders '+((t.orderIds&&t.orderIds.length)||0)+' | hedge '+((t.hedgeOrderIds&&t.hedgeOrderIds.length)||0))+'</div></td><td><div class="row"><strong>'+esc(primaryNote)+'</strong><small class="muted">'+esc(t.question)+(isPaper&&t.shadowLatencyMs!==undefined?' | latency '+esc(i(t.shadowLatencyMs))+'ms':'')+'</small></div></td></tr>'}).join('')}
    function renderActivity(analytics){var items=analytics.activityFeed||[];els.activityCaption.textContent=items.length?'Ultimos '+i(items.length)+' eventos':'Sin actividad';els.activity.innerHTML=items.length?items.map(function(item){return '<article class="feed-item"><strong>'+esc(item.title)+'</strong><div class="muted">'+esc(item.detail)+'</div><small class="muted">'+esc(ts(item.timestamp))+'</small></article>'}).join(''):'<div class="empty">Todavia no hay eventos suficientes para armar el feed.</div>'}
    function renderOpps(analytics){var s=analytics.opportunitySummary,r=analytics.recentOpportunities||[],reasons=(analytics.shadowFillReasons||[]).slice(0,3),near=(analytics.negRiskNearMisses||[]).slice(0,2);els.oppsCaption.textContent=s.total?'Viables '+pct(s.viableRate)+' | avg duration '+(s.averageDurationMs?i(s.averageDurationMs)+' ms':'n/a'):'Sin oportunidades';els.oppCards.innerHTML=[ops('Oportunidades',i(s.total),'Total detectado'),ops('Viables',i(s.viable),'Positivas y ejecutables'),ops('Rejected',i(s.rejected),'No pasaron filtros'),ops('Avg duration',s.averageDurationMs?i(s.averageDurationMs)+' ms':'n/a','Ventana media del edge')].join('');els.rejections.innerHTML=(s.topRejectionReasons||[]).length?(s.topRejectionReasons||[]).map(function(x){return '<div class="item"><strong>'+esc(x.label)+'</strong><div class="muted">Cantidad de rechazos: '+esc(i(x.count))+'</div></div>'}).join(''):'<div class="empty">No hay rechazos relevantes cargados todavia.</div>';els.nearMisses.innerHTML=reasons.length?reasons.map(function(x){return '<div class="item"><strong>'+esc(x.label)+'</strong><div class="muted">Shadow fill reason | '+esc(i(x.count))+' ocurrencias</div></div>'}).join(''):(near.length?near.map(function(o){return '<div class="item"><strong>'+esc(o.slug)+'</strong><div class="muted">Neg-risk near miss | delta '+esc(usd(o.thresholdDeltaUsd||0))+' | spread '+esc(usd(o.rawSpreadUsd||0))+'</div><small class="muted">'+esc('NO cost '+usd(o.sourceNoCostUsd||0)+' | YES proceeds '+usd(o.targetYesProceedsUsd||0)+' | fees '+usd(o.totalFeesUsd||0)+' | gas '+usd(o.gasUsd||0)+' | slip '+usd(o.estimatedSlippageUsd||0))+'</small></div>'}).join(''):'<div class="empty">No hay shadow fill reasons cargados todavia.</div>');els.recentOpps.innerHTML=r.slice(0,4).length?r.slice(0,4).map(function(o){return '<div class="item"><strong>'+esc(o.slug)+'</strong><div class="muted">'+esc(o.viable?'Viable':(o.reason||'Rejected'))+'</div><small class="muted">'+esc(usd(o.expectedProfitUsd))+' | '+esc(ts(o.timestamp))+(o.opportunity_duration_ms!==undefined?' | '+esc(i(o.opportunity_duration_ms))+'ms':'')+'</small></div>'}).join(''):'<div class="empty">Sin oportunidades recientes para mostrar.</div>'}
    function renderOps(payload){var s=payload.snapshot,a=payload.analytics,g=s.tradingGuard||{},enabled=g.tradingEnabled!==false;els.opsCaption.textContent='Uptime '+ago(s.startedAt)+' | last log '+ts(a.lastEventAt);els.opsGrid.innerHTML=[ops('WebSocket',s.scanner.websocketConnected?'Connected':'Disconnected','Last msg '+ago(s.scanner.lastMessageAt)),ops('WS disconnects',i(s.scanner.websocketDisconnects||0),'Reconnects '+i(s.scanner.websocketReconnects||0)),ops('Trading guard',enabled?'Enabled':'Paused',g.pauseReason||'Normal operation'),ops('Resume at',g.resumeAt?ts(g.resumeAt):'n/a','Kill switch window'),ops('Open reservations',i(s.execution.openReservationsCount),s.execution.lastRetainedReservationReason||'No retained reservations'),ops('Reserved notional',usd(s.execution.openNotionalUsd),'Capital currently reserved'),ops('Stale skips',i(s.arbitrage.staleBooksSkipped||0),'Last book age '+(s.arbitrage.lastBookAgeMs!==undefined?i(s.arbitrage.lastBookAgeMs)+'ms':'n/a')),ops('Share fill',pct(s.execution.shareFillRate),'Filled '+n(s.execution.filledShares)+' / '+n(s.execution.intendedShares))].join('');els.errors.innerHTML=(a.recentErrors||[]).length?(a.recentErrors||[]).map(function(e){var origin=[e.source,e.event].filter(Boolean).join(' / ')||'runtime';return '<div class="item"><strong>'+esc(e.message)+'</strong><div class="muted">'+esc(origin)+'</div><small class="muted">'+esc(ago(e.timestamp))+' | '+esc(ts(e.timestamp))+'</small></div>'}).join(''):'<div class="empty">No hay errores recientes en el journal.</div>';els.foot.textContent='Refresh automatico cada 5 segundos. Dashboard de validacion: shadow fills, desconexiones del feed y stale-book skips listos para revisar antes de live.'}
    async function load(){try{var response=await fetch('/api/dashboard',{headers:{accept:'application/json'},cache:'no-store'});if(!response.ok)throw new Error('Dashboard API returned '+response.status);var payload=await response.json();renderHero(payload);renderMetrics(payload);renderChart(payload.analytics);renderStrategies(payload.analytics);renderTrades(payload.analytics);renderActivity(payload.analytics);renderOpps(payload.analytics);renderOps(payload)}catch(error){var msg=error instanceof Error?error.message:'Unknown dashboard error';els.metrics.innerHTML='<div class="empty">No se pudo cargar el dashboard: '+esc(msg)+'</div>'}}
    els.refresh.addEventListener('click',function(){void load()});void load();window.setInterval(function(){void load()},5000);
  </script>
</body>
</html>`;
